/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWishlistRouteImport } from './routes/_dashboard.wishlist'
import { Route as DashboardTutorialsRouteImport } from './routes/_dashboard.tutorials'
import { Route as DashboardTryOnRouteImport } from './routes/_dashboard.try-on'
import { Route as DashboardSubscriptionRouteImport } from './routes/_dashboard.subscription'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardSearchRouteImport } from './routes/_dashboard.search'
import { Route as DashboardScanRouteImport } from './routes/_dashboard.scan'
import { Route as DashboardSavedRouteImport } from './routes/_dashboard.saved'
import { Route as DashboardRecommendationsRouteImport } from './routes/_dashboard.recommendations'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard.notifications'
import { Route as DashboardLooksRouteImport } from './routes/_dashboard.looks'
import { Route as DashboardHistoryRouteImport } from './routes/_dashboard.history'
import { Route as DashboardHelpRouteImport } from './routes/_dashboard.help'
import { Route as DashboardFavoritesRouteImport } from './routes/_dashboard.favorites'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardBeautyProfileRouteImport } from './routes/_dashboard.beauty-profile'
import { Route as DashboardAchievementsRouteImport } from './routes/_dashboard.achievements'
import { Route as DashboardAccountRouteImport } from './routes/_dashboard.account'
import { Route as DashboardScanResultsRouteImport } from './routes/_dashboard.scan.results'
import { Route as DashboardProductIdRouteImport } from './routes/_dashboard.product.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTutorialsRoute = DashboardTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTryOnRoute = DashboardTryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScanRoute = DashboardScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLooksRoute = DashboardLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeautyProfileRoute = DashboardBeautyProfileRouteImport.update({
  id: '/beauty-profile',
  path: '/beauty-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScanResultsRoute = DashboardScanResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardScanRoute,
} as any)
const DashboardProductIdRoute = DashboardProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof DashboardAccountRoute
  '/achievements': typeof DashboardAchievementsRoute
  '/beauty-profile': typeof DashboardBeautyProfileRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/favorites': typeof DashboardFavoritesRoute
  '/help': typeof DashboardHelpRoute
  '/history': typeof DashboardHistoryRoute
  '/looks': typeof DashboardLooksRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/recommendations': typeof DashboardRecommendationsRoute
  '/saved': typeof DashboardSavedRoute
  '/scan': typeof DashboardScanRouteWithChildren
  '/search': typeof DashboardSearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/subscription': typeof DashboardSubscriptionRoute
  '/try-on': typeof DashboardTryOnRoute
  '/tutorials': typeof DashboardTutorialsRoute
  '/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof DashboardProductIdRoute
  '/scan/results': typeof DashboardScanResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof DashboardAccountRoute
  '/achievements': typeof DashboardAchievementsRoute
  '/beauty-profile': typeof DashboardBeautyProfileRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/favorites': typeof DashboardFavoritesRoute
  '/help': typeof DashboardHelpRoute
  '/history': typeof DashboardHistoryRoute
  '/looks': typeof DashboardLooksRoute
  '/notifications': typeof DashboardNotificationsRoute
  '/recommendations': typeof DashboardRecommendationsRoute
  '/saved': typeof DashboardSavedRoute
  '/scan': typeof DashboardScanRouteWithChildren
  '/search': typeof DashboardSearchRoute
  '/settings': typeof DashboardSettingsRoute
  '/subscription': typeof DashboardSubscriptionRoute
  '/try-on': typeof DashboardTryOnRoute
  '/tutorials': typeof DashboardTutorialsRoute
  '/wishlist': typeof DashboardWishlistRoute
  '/product/$id': typeof DashboardProductIdRoute
  '/scan/results': typeof DashboardScanResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_dashboard/account': typeof DashboardAccountRoute
  '/_dashboard/achievements': typeof DashboardAchievementsRoute
  '/_dashboard/beauty-profile': typeof DashboardBeautyProfileRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/favorites': typeof DashboardFavoritesRoute
  '/_dashboard/help': typeof DashboardHelpRoute
  '/_dashboard/history': typeof DashboardHistoryRoute
  '/_dashboard/looks': typeof DashboardLooksRoute
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/_dashboard/saved': typeof DashboardSavedRoute
  '/_dashboard/scan': typeof DashboardScanRouteWithChildren
  '/_dashboard/search': typeof DashboardSearchRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/subscription': typeof DashboardSubscriptionRoute
  '/_dashboard/try-on': typeof DashboardTryOnRoute
  '/_dashboard/tutorials': typeof DashboardTutorialsRoute
  '/_dashboard/wishlist': typeof DashboardWishlistRoute
  '/_dashboard/product/$id': typeof DashboardProductIdRoute
  '/_dashboard/scan/results': typeof DashboardScanResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/account'
    | '/achievements'
    | '/beauty-profile'
    | '/dashboard'
    | '/favorites'
    | '/help'
    | '/history'
    | '/looks'
    | '/notifications'
    | '/recommendations'
    | '/saved'
    | '/scan'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/try-on'
    | '/tutorials'
    | '/wishlist'
    | '/product/$id'
    | '/scan/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/account'
    | '/achievements'
    | '/beauty-profile'
    | '/dashboard'
    | '/favorites'
    | '/help'
    | '/history'
    | '/looks'
    | '/notifications'
    | '/recommendations'
    | '/saved'
    | '/scan'
    | '/search'
    | '/settings'
    | '/subscription'
    | '/try-on'
    | '/tutorials'
    | '/wishlist'
    | '/product/$id'
    | '/scan/results'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_dashboard/account'
    | '/_dashboard/achievements'
    | '/_dashboard/beauty-profile'
    | '/_dashboard/dashboard'
    | '/_dashboard/favorites'
    | '/_dashboard/help'
    | '/_dashboard/history'
    | '/_dashboard/looks'
    | '/_dashboard/notifications'
    | '/_dashboard/recommendations'
    | '/_dashboard/saved'
    | '/_dashboard/scan'
    | '/_dashboard/search'
    | '/_dashboard/settings'
    | '/_dashboard/subscription'
    | '/_dashboard/try-on'
    | '/_dashboard/tutorials'
    | '/_dashboard/wishlist'
    | '/_dashboard/product/$id'
    | '/_dashboard/scan/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/wishlist': {
      id: '/_dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/tutorials': {
      id: '/_dashboard/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof DashboardTutorialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/try-on': {
      id: '/_dashboard/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof DashboardTryOnRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/subscription': {
      id: '/_dashboard/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/search': {
      id: '/_dashboard/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/scan': {
      id: '/_dashboard/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof DashboardScanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/saved': {
      id: '/_dashboard/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/recommendations': {
      id: '/_dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/looks': {
      id: '/_dashboard/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof DashboardLooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/history': {
      id: '/_dashboard/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/help': {
      id: '/_dashboard/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/favorites': {
      id: '/_dashboard/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/beauty-profile': {
      id: '/_dashboard/beauty-profile'
      path: '/beauty-profile'
      fullPath: '/beauty-profile'
      preLoaderRoute: typeof DashboardBeautyProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/achievements': {
      id: '/_dashboard/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account': {
      id: '/_dashboard/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/scan/results': {
      id: '/_dashboard/scan/results'
      path: '/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof DashboardScanResultsRouteImport
      parentRoute: typeof DashboardScanRoute
    }
    '/_dashboard/product/$id': {
      id: '/_dashboard/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof DashboardProductIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardScanRouteChildren {
  DashboardScanResultsRoute: typeof DashboardScanResultsRoute
}

const DashboardScanRouteChildren: DashboardScanRouteChildren = {
  DashboardScanResultsRoute: DashboardScanResultsRoute,
}

const DashboardScanRouteWithChildren = DashboardScanRoute._addFileChildren(
  DashboardScanRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardBeautyProfileRoute: typeof DashboardBeautyProfileRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardLooksRoute: typeof DashboardLooksRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardScanRoute: typeof DashboardScanRouteWithChildren
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardTryOnRoute: typeof DashboardTryOnRoute
  DashboardTutorialsRoute: typeof DashboardTutorialsRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardProductIdRoute: typeof DashboardProductIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardBeautyProfileRoute: DashboardBeautyProfileRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardLooksRoute: DashboardLooksRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardScanRoute: DashboardScanRouteWithChildren,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardTryOnRoute: DashboardTryOnRoute,
  DashboardTutorialsRoute: DashboardTutorialsRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardProductIdRoute: DashboardProductIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
